const song = {
  name: "Home",
  verse_list: [0, 10, 20, 30],
  pnm_list: [
    {
      text: "(playing home from undertale)",
      style: "monika_credits_text",
      notes: ([] as string[])
        .concat([
          "E4",
          "D4",
          "B3",
          "B3",
          "",
          "E4",
          "D4",
          "B3",
          "B3",
          "",
          "E4",
          "D4",
          "B3",
          "B3",
          "",
          "B3",
          "D4",
          "G3",
          "G3",
          "",
          "E4",
          "D4",
          "B3",
          "A3",
          "G3",
          "",
          "E4",
          "D4",
          "B3",
          "B3",
          "",
          "E4",
          "D4",
          "B3",
          "A3",
          "G3",
          "A3",
          "B3",
          "D4",
          "E3",
          "",
        ])
        .concat(
          [] || [
              "C3",
              "C3SH",
              "D3",
              "D3SH",
              "E3",
              "F3",
              "F3SH",
              "G3",
              "G3SH",
              "A3",
              "A3SH",
              "B3",
            ] || ["C4", "C5", "C6", "B6", "C3", "C4", "C5", "C6", "B6"]
        )
        .concat(
          [] || [
            "F4",
            "A4SH",
            "C5",
            "D5",
            "A4SH",
            "C5",
            "D5",
            "G4",
            "A4SH",
            "C5",
            "F5",
            "A4SH",
            "C5",
            "D5",
            "A4SH",
            "C5",
            "F5",
            "F4",
            "A4SH",
            "C5",
            "D5",
            "A4SH",
            "C5",
            "D5",
            "G4",
            "A4SH",
            "C5",
            "D5",
            "A4SH",
            "C5",
            "D5",
            "A4",
            "A4SH",
            "C5",
            "F5",
            "A4SH",
            "C5",
            "D5",
          ]
        ),
      express: "1eub",
      postexpress: "1eua",
      vis_timeout: 2.0,
      verse: 0,
      posttext: true,
    },
    {
      text: "(Playing home from undertale)",
      style: "monika_credits_text",
      notes: [
        "A4SH",
        "C5",
        "A4SH",
        "F4",
        "A4SH",
        "C5",
        "D5",
        "A4SH",
        "C5",
        "D5",
        "G4",
        "A4SH",
        "C5",
        "D5",
        "A4SH",
        "C5",
        "D5",
        "F4SH",
        "A4SH",
        "C5",
        "D5",
      ],
      postnotes: ["F4SH", "A4SH", "D5", "A4SH", "A4SH", "C5", "A4SH"],
      express: "1eub",
      postexpress: "1eua",
      ev_timeout: 1.0,
    },
  ],
};

export default song.pnm_list[0].notes
  .reverse()
  .map((note) => note.replace(/(\d)SH/, "#$1"));
